# Generated by Django 4.2.30 on 2026-06-20 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyview',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='annonces.annonce'),
        ),
        migrations.AddField(
            model_name='propertyview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyperformance',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['annonce', 'viewed_at'], name='analytics_p_annonce_6b78db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyperformance',
            unique_together={('agency', 'month')},
        ),
    ]
