# Generated by Django 4.2.30 on 2026-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identifiant de session (cookie/anonyme ou user-based)', max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Utilisateur'), ('ai', 'Assistant IA')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message IA',
                'verbose_name_plural': 'Messages IA',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(blank=True, help_text='Score de pertinence renvoyé par N8N (0 à 1)', null=True)),
                ('was_clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommandation IA',
                'verbose_name_plural': 'Recommandations IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
