# Generated by Django 4.2.30 on 2026-06-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
        ('ai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='annonces.annonce'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai_integration.aiconversation'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_integration.aiconversation'),
        ),
    ]
