# Generated by Django 4.2.30 on 2026-06-20 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_integration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null si visiteur anonyme', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
