# Generated by Django 4.2.30 on 2026-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('annonce_approved', 'Annonce approuvée'), ('annonce_rejected', 'Annonce rejetée'), ('user_suspended', 'Utilisateur suspendu'), ('user_verified', 'Utilisateur vérifié'), ('annonce_deleted', 'Annonce supprimée')], max_length=30)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-created_at'],
            },
        ),
    ]
