# Generated by Django 4.2.11 on 2026-07-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0003_alter_visitrequest_options_and_more'),
        ('admin_dashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateTimeField(blank=True, null=True)),
                ('owner_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action', to='client_dashboard.visitrequest')),
            ],
        ),
    ]
