# Generated by Django 4.2.11 on 2026-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_visitrequestaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequestaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitrequestaction',
            name='is_seen_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitrequestaction',
            name='is_seen_by_owner',
            field=models.BooleanField(default=True),
        ),
    ]
