# Generated by Django 4.2.30 on 2026-06-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_cities', models.CharField(blank=True, help_text='Villes préférées, séparées par des virgules', max_length=255)),
                ('preferred_property_types', models.CharField(blank=True, help_text='Types de biens préférés, séparés par des virgules', max_length=255)),
                ('budget_range', models.CharField(blank=True, choices=[('under_1m', 'Moins de 1M MAD'), ('1m_3m', '1M – 3M MAD'), ('3m_6m', '3M – 6M MAD'), ('above_6m', '6M+ MAD')], max_length=20)),
                ('is_looking_to_buy', models.BooleanField(default=True)),
                ('is_looking_to_rent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=20)),
                ('transaction_type', models.CharField(blank=True, max_length=10)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notify_by_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recherche sauvegardée',
                'verbose_name_plural': 'Recherches sauvegardées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(verbose_name='Date souhaitée')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Effectuée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='annonces.annonce')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'verbose_name_plural': 'Demandes de visite',
                'ordering': ['-created_at'],
            },
        ),
    ]
