# Generated by Django 4.2.11 on 2026-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitrequest',
            options={},
        ),
        migrations.RenameField(
            model_name='visitrequest',
            old_name='message',
            new_name='owner_message',
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='requested_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rescheduled', 'Nouvelle date proposée'), ('refused', 'Refusée'), ('completed', 'Effectuée')], default='pending', max_length=20),
        ),
    ]
