# Generated by Django 4.2.11 on 2026-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0003_alter_visitrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='client_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
