# Generated by Django 4.2.30 on 2026-06-20 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('riad', 'Riad'), ('maison', 'Maison'), ('terrain', 'Terrain')], max_length=20, verbose_name='Type de bien')),
                ('transaction_type', models.CharField(choices=[('vente', 'À Vendre'), ('location', 'À Louer')], max_length=10, verbose_name='Type de transaction')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('published', 'Publiée'), ('sold', 'Vendue'), ('rented', 'Louée'), ('archived', 'Archivée')], default='pending', max_length=12, verbose_name='Statut')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=150, verbose_name='Quartier')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (MAD)')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surface (m²)')),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Chambres')),
                ('bathrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Salles de bain')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Piscine')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Jardin')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Meublé')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_boosted', models.BooleanField(default=False, verbose_name='Boosté (payant)')),
                ('boosted_until', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.annonce')),
            ],
            options={
                'verbose_name': "Photo d'annonce",
                'verbose_name_plural': "Photos d'annonces",
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
