# Generated by Django 4.2.30 on 2026-06-20 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['city', 'property_type'], name='annonces_an_city_ce82aa_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['transaction_type', 'status'], name='annonces_an_transac_a0bebb_idx'),
        ),
    ]
