# Generated by Django 4.2.11 on 2026-06-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_alter_annonce_latitude_alter_annonce_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
